# Sweet Shop ERP - Directory and File Creator for Windows 11

$base = Get-Location

# Directories
$dirs = @(
    "app\Http\Controllers",
    "app\Http\Middleware",
    "app\Http\Requests",
    "app\Models",
    "app\Repositories",
    "app\Services",
    "database\migrations",
    "database\seeders",
    "resources\views\layouts",
    "resources\views\categories",
    "resources\views\units",
    "resources\views\items",
    "resources\views\suppliers",
    "resources\views\purchases",
    "resources\views\purchase_returns",
    "resources\views\recipes",
    "resources\views\production_logs",
    "resources\views\sales",
    "resources\views\sale_returns",
    "resources\views\expenses",
    "resources\views\reports",
    "resources\lang\en",
    "resources\lang\hi"
)

foreach ($dir in $dirs) {
    New-Item -ItemType Directory -Force -Path "$base\$dir" | Out-Null
    Write-Host "Created: $dir"
}

# Files (empty stubs – you will paste code from chat)
$files = @(
    "app\Http\Controllers\CategoryController.php",
    "app\Http\Controllers\UnitController.php",
    "app\Http\Controllers\ItemController.php",
    "app\Http\Controllers\SupplierController.php",
    "app\Http\Controllers\PurchaseController.php",
    "app\Http\Controllers\PurchaseReturnController.php",
    "app\Http\Controllers\RecipeController.php",
    "app\Http\Controllers\ProductionLogController.php",
    "app\Http\Controllers\SaleController.php",
    "app\Http\Controllers\SaleReturnController.php",
    "app\Http\Controllers\ExpenseController.php",
    "app\Http\Controllers\ReportController.php",
    "app\Http\Middleware\RoleMiddleware.php",
    "app\Http\Middleware\PermissionMiddleware.php",
    "app\Http\Middleware\FeatureMiddleware.php",
    "app\Http\Requests\CategoryRequest.php",
    "app\Http\Requests\UnitRequest.php",
    "app\Http\Requests\ItemRequest.php",
    "app\Http\Requests\SupplierRequest.php",
    "app\Http\Requests\PurchaseRequest.php",
    "app\Http\Requests\PurchaseReturnRequest.php",
    "app\Http\Requests\RecipeRequest.php",
    "app\Http\Requests\ProductionLogRequest.php",
    "app\Http\Requests\SaleRequest.php",
    "app\Http\Requests\SaleReturnRequest.php",
    "app\Http\Requests\ExpenseRequest.php",
    "app\Models\User.php",
    "app\Models\Role.php",
    "app\Models\Permission.php",
    "app\Models\RolePermission.php",
    "app\Models\UserRole.php",
    "app\Models\Category.php",
    "app\Models\Unit.php",
    "app\Models\TaxRate.php",
    "app\Models\Item.php",
    "app\Models\StockLedger.php",
    "app\Models\Supplier.php",
    "app\Models\Purchase.php",
    "app\Models\PurchaseItem.php",
    "app\Models\PurchaseReturn.php",
    "app\Models\PurchaseReturnItem.php",
    "app\Models\Recipe.php",
    "app\Models\RecipeIngredient.php",
    "app\Models\ProductionLog.php",
    "app\Models\Customer.php",
    "app\Models\Sale.php",
    "app\Models\SaleItem.php",
    "app\Models\SalePayment.php",
    "app\Models\SaleReturn.php",
    "app\Models\SaleReturnItem.php",
    "app\Models\Expense.php",
    "app\Models\Account.php",
    "app\Models\JournalEntry.php",
    "app\Models\Setting.php",
    "app\Models\FeaturePermission.php",
    "app\Repositories\CategoryRepository.php",
    "app\Repositories\UnitRepository.php",
    "app\Repositories\ItemRepository.php",
    "app\Repositories\SupplierRepository.php",
    "app\Repositories\PurchaseRepository.php",
    "app\Repositories\PurchaseReturnRepository.php",
    "app\Repositories\RecipeRepository.php",
    "app\Repositories\ProductionLogRepository.php",
    "app\Repositories\SaleRepository.php",
    "app\Repositories\SaleReturnRepository.php",
    "app\Repositories\ExpenseRepository.php",
    "app\Services\CategoryService.php",
    "app\Services\UnitService.php",
    "app\Services\ItemService.php",
    "app\Services\SupplierService.php",
    "app\Services\PurchaseService.php",
    "app\Services\PurchaseReturnService.php",
    "app\Services\RecipeService.php",
    "app\Services\ProductionLogService.php",
    "app\Services\SaleService.php",
    "app\Services\SaleReturnService.php",
    "app\Services\ExpenseService.php",
    "database\migrations\0001_01_01_000001_create_users_table.php",
    "database\migrations\0002_01_01_000002_create_roles_table.php",
    "database\migrations\0003_01_01_000003_create_permissions_table.php",
    "database\migrations\0004_01_01_000004_create_role_permissions_table.php",
    "database\migrations\0005_01_01_000005_create_user_roles_table.php",
    "database\migrations\0006_01_01_000006_create_categories_table.php",
    "database\migrations\0007_01_01_000007_create_units_table.php",
    "database\migrations\0008_01_01_000008_create_tax_rates_table.php",
    "database\migrations\0009_01_01_000009_create_items_table.php",
    "database\migrations\0010_01_01_000010_create_stock_ledger_table.php",
    "database\migrations\0011_01_01_000011_create_suppliers_table.php",
    "database\migrations\0012_01_01_000012_create_purchases_table.php",
    "database\migrations\0013_01_01_000013_create_purchase_items_table.php",
    "database\migrations\0014_01_01_000014_create_purchase_returns_table.php",
    "database\migrations\0015_01_01_000015_create_purchase_return_items_table.php",
    "database\migrations\0016_01_01_000016_create_recipes_table.php",
    "database\migrations\0017_01_01_000017_create_recipe_ingredients_table.php",
    "database\migrations\0018_01_01_000018_create_production_logs_table.php",
    "database\migrations\0019_01_01_000019_create_customers_table.php",
    "database\migrations\0020_01_01_000020_create_sales_table.php",
    "database\migrations\0021_01_01_000021_create_sale_items_table.php",
    "database\migrations\0022_01_01_000022_create_sale_payments_table.php",
    "database\migrations\0023_01_01_000023_create_sale_returns_table.php",
    "database\migrations\0024_01_01_000024_create_sale_return_items_table.php",
    "database\migrations\0025_01_01_000025_create_expenses_table.php",
    "database\migrations\0026_01_01_000026_create_accounts_table.php",
    "database\migrations\0027_01_01_000027_create_journal_entries_table.php",
    "database\migrations\0028_01_01_000028_create_settings_table.php",
    "database\migrations\0029_01_01_000029_create_feature_permissions_table.php",
    "database\seeders\PermissionSeeder.php",
    "database\seeders\RoleAndUserSeeder.php",
    "database\seeders\FeaturePermissionSeeder.php",
    "resources\views\layouts\admin.blade.php",
    "resources\views\categories\index.blade.php",
    "resources\views\categories\create.blade.php",
    "resources\views\categories\edit.blade.php",
    "resources\views\units\index.blade.php",
    "resources\views\units\create.blade.php",
    "resources\views\units\edit.blade.php",
    "resources\views\items\index.blade.php",
    "resources\views\items\create.blade.php",
    "resources\views\items\edit.blade.php",
    "resources\lang\en\messages.php",
    "resources\lang\hi\messages.php",
    "routes\web.php"
)

foreach ($file in $files) {
    New-Item -ItemType File -Force -Path "$base\$file" | Out-Null
    Write-Host "Created: $file"
}

Write-Host "`n✅ All directories and empty files have been created."
Write-Host "Now open each file and paste the code from the chat conversation."